export const projects = [
  {
    id: "elite-fitness",
    title: "Elite Fitness",
    category: "web",
    categoryLabel: "Landing Page",
    status: "Projeto demonstrativo",
    description:
      "Landing page responsiva para academia, focada em modalidades, estrutura, prova social e agendamento de aula experimental.",
    problem:
      "Academias precisam apresentar sua estrutura e diferenciais com clareza, em uma experiência rápida para visitantes de qualquer dispositivo.",
    solution:
      "Uma página de alta conversão com hierarquia visual esportiva, mapa integrado, contato direto e navegação acessível.",
    challenges:
      "Equilibrar energia visual, responsividade, carregamento de imagens, acessibilidade e chamadas para ação sem excesso de informação.",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap Icons", "Responsive Design"],
    gradient: "linear-gradient(135deg,#190303,#ff2d2d 54%,#ffd60a)",
    github: "",
    demo: "projects/elite-fitness/index.html",
  },
  {
    id: "advocacia",
    title: "Oliveira & Associados",
    category: "web",
    categoryLabel: "Landing Page",
    status: "Projeto demonstrativo",
    description:
      "Landing page responsiva para escritório de advocacia, com áreas de atuação, diferenciais, depoimentos ilustrativos, FAQ e contato.",
    problem:
      "Apresentar serviços jurídicos extensos com clareza e conduzir o visitante aos canais de contato em qualquer dispositivo.",
    solution:
      "Uma experiência sóbria e objetiva, com hierarquia visual, navegação por seções, conteúdo acessível e chamadas para ação responsivas.",
    challenges:
      "Organizar grande volume de conteúdo sem perder legibilidade, padronizar ícones e eliminar cortes ou rolagem horizontal em telas pequenas.",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap Icons", "Responsive Design"],
    gradient: "linear-gradient(135deg,#0d1b2a,#1b263b 58%,#d4af37)",
    github: "",
    demo: "https://advocacia-flame.vercel.app/",
  },
  {
    id: "clinica-estetica",
    title: "Belezza Estética",
    category: "web",
    categoryLabel: "Landing Page",
    status: "Projeto demonstrativo",
    description:
      "Landing page responsiva para clínica de estética, com tratamentos, resultados ilustrativos, benefícios, FAQ e canais de contato.",
    problem:
      "Apresentar muitos tratamentos e diferenciais com clareza, sem perder legibilidade ou confiança em telas menores.",
    solution:
      "Uma experiência acolhedora e objetiva, com conteúdo demonstrativo identificado, hierarquia visual, navegação acessível e chamadas responsivas.",
    challenges:
      "Padronizar ícones, tornar menu e FAQ acessíveis e eliminar cortes e rolagem horizontal preservando a identidade visual.",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap Icons", "Responsive Design"],
    gradient: "linear-gradient(135deg,#4a164b,#9d4edd 56%,#f7a8c4)",
    github: "",
    demo: "https://clinica-estetica-seven-ashen.vercel.app/",
  },
  {
    id: "clinica-medica",
    title: "Dra. Camila Nutri",
    category: "web",
    categoryLabel: "Landing Page",
    status: "Projeto demonstrativo",
    description:
      "Landing page responsiva para atendimento nutricional, com serviços, resultados ilustrativos, benefícios, FAQ e canais de contato.",
    problem:
      "Organizar serviços e informações de saúde com clareza, evitando sobrecarga visual e ações fictícias em diferentes dispositivos.",
    solution:
      "Uma experiência acolhedora, responsiva e acessível, com conteúdo demonstrativo identificado e navegação objetiva.",
    challenges:
      "Padronizar ícones, tornar menu e FAQ acessíveis e preservar o conteúdo sem apresentar alegações clínicas fictícias como reais.",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap Icons", "Responsive Design"],
    gradient: "linear-gradient(135deg,#163b2b,#2d6a4f 56%,#b7e4c7)",
    github: "",
    demo: "https://clinica-medica-lyart.vercel.app/",
  },
  {
    id: "coach-consultor",
    title: "Marcos Ribeiro",
    category: "web",
    categoryLabel: "Landing Page",
    status: "Projeto demonstrativo",
    description:
      "Landing page responsiva para coach e consultor, com serviços, galeria, benefícios, depoimentos ilustrativos, FAQ e contato.",
    problem:
      "Apresentar muitos serviços e diferenciais profissionais sem perder clareza, confiança ou facilidade de navegação em telas menores.",
    solution:
      "Uma experiência profissional e responsiva, com conteúdo demonstrativo identificado, hierarquia visual forte e chamadas para ação acessíveis.",
    challenges:
      "Padronizar ícones, tornar menu e FAQ acessíveis e eliminar cortes e rolagem horizontal preservando a identidade visual.",
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap Icons", "Responsive Design"],
    gradient: "linear-gradient(135deg,#111827,#1d4ed8 56%,#f59e0b)",
    github: "",
    demo: "https://coach-consultor-psi.vercel.app/",
  },
  {
    id: "landing-premium",
    title: "Landing Page Premium",
    category: "web",
    categoryLabel: "Web & UX",
    status: "Projeto conceitual",
    description:
      "Página empresarial orientada à apresentação de serviços, conversão e experiência responsiva.",
    problem:
      "Negócios precisam comunicar valor rapidamente sem sobrecarregar o visitante.",
    solution:
      "Uma jornada objetiva, com hierarquia visual, prova de valor e chamadas para ação claras.",
    challenges:
      "Equilibrar impacto visual, performance, acessibilidade e conversão.",
    technologies: ["HTML", "CSS", "JavaScript", "UI/UX"],
    gradient: "linear-gradient(135deg,#014040,#03A688 58%,#C2F2CE)",
    github: "",
    demo: "projeto/index.html",
  },
  {
    id: "crm-clientes",
    title: "CRM de Clientes",
    category: "systems",
    categoryLabel: "Sistema Web",
    status: "Em desenvolvimento",
    description:
      "Sistema para cadastrar, buscar, editar e acompanhar clientes e seus históricos.",
    problem:
      "Informações comerciais dispersas tornam o acompanhamento lento e impreciso.",
    solution:
      "Centralização de dados, filtros, histórico e status em uma interface direta.",
    challenges:
      "Organização de informação, busca rápida e estados de relacionamento.",
    technologies: ["JavaScript", "JSON", "DOM", "UI/UX"],
    gradient: "linear-gradient(135deg,#012f36,#A60303 120%)",
    github: "",
    demo: "",
  },
  {
    id: "sistema-estoque",
    title: "Sistema de Estoque",
    category: "systems",
    categoryLabel: "Dashboard",
    status: "Projeto conceitual",
    description:
      "Controle de produtos, entradas, saídas, estoque mínimo, alertas e filtros.",
    problem:
      "A falta de visibilidade sobre movimentações pode gerar perdas e decisões tardias.",
    solution:
      "Dashboard com visão operacional, alertas e rastreabilidade de alterações.",
    challenges: "Representar estados críticos sem criar ruído visual.",
    technologies: ["JavaScript", "JSON", "Dados", "Dashboard"],
    gradient: "linear-gradient(135deg,#014040,#D96704)",
    github: "",
    demo: "",
  },
  {
    id: "ecommerce-dashboard",
    title: "E-commerce Dashboard",
    category: "systems",
    categoryLabel: "Produto Digital",
    status: "Projeto conceitual",
    description:
      "Painel administrativo para produtos, pedidos, estoque, vendas e indicadores.",
    problem:
      "Operações digitais exigem uma leitura unificada de vendas e catálogo.",
    solution:
      "Módulos conectados com indicadores essenciais, filtros e ações rápidas.",
    challenges:
      "Criar densidade informacional mantendo clareza e responsividade.",
    technologies: ["HTML", "CSS", "JavaScript", "Dados"],
    gradient: "linear-gradient(135deg,#6d0202,#D96704 70%,#014040)",
    github: "",
    demo: "",
  },
  {
    id: "painel-administrativo",
    title: "Painel Administrativo",
    category: "systems",
    categoryLabel: "Sistema Web",
    status: "Projeto conceitual",
    description:
      "Gestão de usuários, permissões, informações, status e relatórios.",
    problem:
      "Equipes precisam controlar acessos e processos com segurança e transparência.",
    solution:
      "Arquitetura modular com permissões, estados e trilhas de ação compreensíveis.",
    challenges: "Permissões, escalabilidade da interface e prevenção de erros.",
    technologies: ["JavaScript", "UI/UX", "Segurança", "APIs"],
    gradient: "linear-gradient(135deg,#021d22,#03A688 80%)",
    github: "",
    demo: "",
  },
  {
    id: "gestao-equipe",
    title: "Gestão de Equipe",
    category: "systems",
    categoryLabel: "Gestão",
    status: "Projeto conceitual",
    description:
      "Dashboard para colaboradores, áreas, habilidades, projetos e tarefas.",
    problem:
      "Sem contexto compartilhado, responsabilidades e competências ficam pouco visíveis.",
    solution: "Visão integrada de pessoas, entregas e capacidades da equipe.",
    challenges: "Apresentar relações complexas em uma experiência simples.",
    technologies: ["JavaScript", "JSON", "Dashboard", "UX"],
    gradient: "linear-gradient(135deg,#014040,#A60303)",
    github: "",
    demo: "",
  },
  {
    id: "mobile-productivity",
    title: "Aplicativo Mobile Concept",
    category: "web",
    categoryLabel: "Mobile-first",
    status: "Projeto conceitual",
    description:
      "Experiência mobile-first para produtividade, organização e rotina profissional.",
    problem:
      "Ferramentas complexas afastam usuários que precisam registrar e priorizar rapidamente.",
    solution:
      "Fluxos curtos, navegação por contexto e visualização clara das prioridades.",
    challenges: "Ergonomia de toque, espaços reduzidos e uso em movimento.",
    technologies: ["HTML", "CSS", "JavaScript", "Mobile UX"],
    gradient: "linear-gradient(135deg,#03A688,#014040 70%,#D96704)",
    github: "",
    demo: "",
  },
  {
    id: "desktop-management",
    title: "Desktop Management App",
    category: "systems",
    categoryLabel: "Desktop Concept",
    status: "Projeto conceitual",
    description:
      "Interface desktop para arquivos, projetos, produtividade e gestão.",
    problem:
      "Fluxos profissionais extensos precisam de organização sem excesso de navegação.",
    solution:
      "Ambiente de trabalho modular, com atalhos e visão consistente dos projetos.",
    challenges: "Hierarquia, atalhos, múltiplos painéis e estados vazios.",
    technologies: ["UI/UX", "JavaScript", "Arquitetura visual"],
    gradient: "linear-gradient(135deg,#032b2b,#D96704)",
    github: "",
    demo: "",
  },
  {
    id: "data-automation",
    title: "Data Automation Tool",
    category: "data",
    categoryLabel: "Dados & Automação",
    status: "Em desenvolvimento",
    description:
      "Ferramenta para organizar, filtrar, transformar e validar conjuntos de dados.",
    problem:
      "Tarefas manuais repetitivas aumentam tempo de operação e risco de inconsistência.",
    solution:
      "Fluxo configurável de importação, tratamento, validação e exportação.",
    challenges:
      "Integridade dos dados, feedback de erros e flexibilidade de formatos.",
    technologies: ["Python", "JSON", "Manipulação de dados", "Automação"],
    gradient: "linear-gradient(135deg,#014040,#03A688,#C2F2CE)",
    github: "",
    demo: "",
  },
  {
    id: "interactive-3d",
    title: "Interactive 3D Experience",
    category: "experimental",
    categoryLabel: "Creative Development",
    status: "Experimento conceitual",
    description:
      "Narrativa experimental combinando scroll, profundidade, interação e movimento.",
    problem:
      "Experiências digitais podem informar sem deixar de despertar curiosidade.",
    solution:
      "Uma sequência controlada pelo visitante que conecta conteúdo e transformação visual.",
    challenges:
      "Performance, acessibilidade, dispositivos fracos e redução de movimento.",
    technologies: ["JavaScript", "CSS 3D", "Canvas", "Interação"],
    gradient: "linear-gradient(135deg,#020b0b,#A60303 55%,#D96704)",
    github: "",
    demo: "",
  },
  {
    id: "consultorio-odontologico",
    title: "Odonto Sorriso",
    category: "web",
    categoryLabel: "Clínica odontológica",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para clínica odontológica, com tratamentos, estrutura, benefícios, depoimentos ilustrativos, FAQ e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#075985,#0ea5e9 58%,#bae6fd)",
    github: "https://github.com/rafael192612/consultorio-odontologico",
    demo: "https://consultorio-odontologico-zeta-seven.vercel.app/",
  },
  {
    id: "contabilidade",
    title: "ContaPro Contabilidade",
    category: "web",
    categoryLabel: "Contabilidade",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para escritório contábil, com serviços, diferenciais, soluções empresariais, FAQ e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#0f172a,#0f766e 58%,#99f6e4)",
    github: "https://github.com/rafael192612/contabilidade",
    demo: "https://contabilidade-tau-red.vercel.app/",
  },
  {
    id: "escola-idiomas",
    title: "Global Languages",
    category: "web",
    categoryLabel: "Escola de idiomas",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para escola de idiomas, com cursos, metodologia, benefícios, depoimentos ilustrativos, FAQ e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#172554,#2563eb 58%,#facc15)",
    github: "https://github.com/rafael192612/escola-idiomas",
    demo: "https://escola-idiomas-lyart.vercel.app/",
  },
  {
    id: "imobiliaria",
    title: "Prime Imóveis",
    category: "web",
    categoryLabel: "Imobiliária",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para imobiliária, com imóveis em destaque, serviços, diferenciais, busca e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#111827,#b45309 58%,#fde68a)",
    github: "https://github.com/rafael192612/imobiliaria",
    demo: "https://imobiliaria-phi-jet.vercel.app/",
  },
  {
    id: "infoprodutor",
    title: "Lucas Ferreira",
    category: "web",
    categoryLabel: "Infoprodutor",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para infoprodutor e mentor digital, com oferta, método, benefícios, prova ilustrativa e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#1e1b4b,#7c3aed 58%,#f0abfc)",
    github: "https://github.com/rafael192612/infoprodutor",
    demo: "https://infoprodutor-weld.vercel.app/",
  },
  {
    id: "loja-roupa",
    title: "Bella Moda",
    category: "web",
    categoryLabel: "Loja de roupa",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para boutique de moda feminina, com coleções, produtos, diferenciais e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#4c0519,#db2777 58%,#fbcfe8)",
    github: "https://github.com/rafael192612/loja-roupa",
    demo: "https://loja-roupa-kappa.vercel.app/",
  },
  {
    id: "oficina-mecanica",
    title: "Auto Center Premium",
    category: "web",
    categoryLabel: "Oficina mecânica",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para oficina mecânica, com serviços, diferenciais, confiança, FAQ e agendamento.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#111827,#dc2626 58%,#f59e0b)",
    github: "https://github.com/rafael192612/oficina-mecanica",
    demo: "https://oficina-mecanica-blue.vercel.app/",
  },
  {
    id: "petshop",
    title: "Patinhas Pet Shop & Vet",
    category: "web",
    categoryLabel: "Petshop",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para petshop e clínica veterinária, com serviços, cuidados, benefícios e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#14532d,#22c55e 58%,#fde047)",
    github: "https://github.com/rafael192612/petshop",
    demo: "https://petshop-lake-seven.vercel.app/",
  },
  {
    id: "restaurante",
    title: "Sabor da Vila",
    category: "web",
    categoryLabel: "Restaurante",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para pizzaria artesanal, com cardápio, diferenciais, ambiente, delivery e contato.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#3f0d0d,#dc2626 58%,#fbbf24)",
    github: "https://github.com/rafael192612/restaurante",
    demo: "https://restaurante-gold-one.vercel.app/",
  },
  {
    id: "salao-beleza",
    title: "Studio Hair & Beauty",
    category: "web",
    categoryLabel: "Salão de beleza",
    status: "Projeto demonstrativo",
    description: "Landing page demonstrativa para salão de beleza e barbearia, com serviços, equipe, benefícios e agendamento.",
    problem: "Apresentar serviços, diferenciais e canais de contato com clareza em qualquer dispositivo.",
    solution: "Uma experiência responsiva, acessível e orientada à conversão, com navegação objetiva e chamadas para ação.",
    challenges: "Organizar o conteúdo, preservar a identidade visual e eliminar cortes ou rolagem horizontal em telas menores.",
    technologies: ["HTML", "CSS", "JavaScript", "Responsive Design"],
    gradient: "linear-gradient(135deg,#18181b,#a855f7 58%,#f5d0fe)",
    github: "https://github.com/rafael192612/salao-beleza",
    demo: "https://salao-beleza-inky.vercel.app/",
  },
];
